name       : giflib
version    : 5.1.4
release    : 8
source     :
    - https://netix.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.bz2 : df27ec3ff24671f80b29e6ab1c4971059c14ac3db95406884fc26574631ba8d5
homepage   : http://giflib.sourceforge.net/
license    : MIT
component  : desktop.library
summary    : GIFLIB is a package of portable tools and library routines for working with GIF images
description: |
    The giflib package contains a shared library of functions for loading and saving GIF format image files. It is API and ABI compatible with libungif, the library which supported uncompressed GIFs while the Unisys LZW patent was in effect.
builddeps  :
    - pkgconfig(gl) # check
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make -j1 check
