name        : giflib
version     : 4.1.6
release     : 6
source      :
    - http://ufpr.dl.sourceforge.net/project/giflib/giflib-4.x/giflib-4.1.6/giflib-4.1.6.tar.bz2 : e1c1ced9c5bc8f93ef0faf0a8c7717abf784d10a7b270d2285e8e1f3b93f2bed
homepage    : http://sourceforge.net/projects/giflib/
license     : MIT
component   : desktop.library
summary     : GIFLIB is a package of portable tools and library routines for working with GIF images.
description : |
    The giflib package contains a shared library of functions for loading and saving GIF format image files. It is API and ABI compatible with libungif, the library which supported uncompressed GIFs while the Unisys LZW patent was in effect.
builddeps   :
    - pkgconfig(gl)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
